fixtures:
  symlinks:
    stash: "#{source_dir}"
  repositories:
    deploy: "https://github.com/mkrakowitzer/puppet-deploy"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    repoforge: "https://github.com/Mylezeem/puppet-repoforge.git"
